DROP TABLE MENU CASCADE CONSTRAINTS;
DROP TABLE RESERVAS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE PLATOS CASCADE CONSTRAINTS;
DROP TABLE INGREDIENTES CASCADE CONSTRAINTS;
DROP TABLE MENU_PLATOS CASCADE CONSTRAINTS;

CREATE TABLE MENU(
    ID_MENU NUMBER(4) NOT NULL,/*PK*/
    PRECIO NUMBER(5),
    FECHA_INIC DATE,
    FECHA_FIN DATE
);

CREATE TABLE MENU_PLATOS(
    ID_MENU NUMBER(4) NOT NULL,/*PK & FK*/
    ID_PLATOS NUMBER(4) NOT NULL/*PK & FK*/
);

CREATE TABLE PLATOS(
    ID_PLATOS NUMBER(4) NOT NULL,/*PK*/
    NOMBRE VARCHAR2(16) NOT NULL,
    TIPO VARCHAR2(16) NOT NULL,
    ID_INGREDIENTE NUMBER(4) NOT NULL/*FK*/
);

CREATE TABLE RESERVAS(
    ID_RESERVA NUMBER(4) NOT NULL,/*PK*/
    HORA_RESERVA TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    FECHA_RESERVA DATE NOT NULL,
    Nº_PERSONAS NUMBER(4) NOT NULL,
    OBSERVACIONES VARCHAR2(200),
    ALERGENOS VARCHAR2(100),
    ID_CLIENTE NUMBER(4) NOT NULL,/*FK*/
    ID_MENU NUMBER(4) NOT NULL/*FK*/
);

CREATE TABLE CLIENTES(
    ID_CLIENTE NUMBER(4) NOT NULL,/*PK*/
    NOMBRE_CLIENTE VARCHAR(16) NOT NULL,
    TELEFONO VARCHAR2 (11) NOT NULL,
    EMAIL VARCHAR2 (30) NOT NULL
);


CREATE TABLE INGREDIENTES(
    ID_INGREDIENTE NUMBER(4) NOT NULL,/*PK*/
    NOMBRE VARCHAR2(16) NOT NULL,
    ALERGENOS VARCHAR2(30) CHECK( ALERGENOS IN ('NINGUNO','GLUTEN','CRUSTACEOS', 'MOLUSCOS', 'PESCADO', 'HUEVOS', 'ALTRAMUCES', 'MOSTAZA', 'CACAHUETES', 'FRUTOS SECOS', 'SOJA', 'SESAMO', 'APIO', 'LECHE', 'ANHIDRIDO SULFUROSO') )
);

/*CREACION DE LAS PK*/
ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY(ID_MENU);

ALTER TABLE MENU_PLATOS ADD CONSTRAINT PK_MENU_PLATOS PRIMARY KEY(ID_MENU, ID_PLATOS);

ALTER TABLE PLATOS ADD CONSTRAINT PK_PLATOS PRIMARY KEY(ID_PLATOS);

ALTER TABLE RESERVAS ADD CONSTRAINT PK_RESERVAS PRIMARY KEY(ID_RESERVA, ID_CLIENTE, ID_MENU);

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY(ID_CLIENTE);

ALTER TABLE INGREDIENTES ADD CONSTRAINT PK_INGREDIENTES PRIMARY KEY(ID_INGREDIENTE);

/*CREACION DE LAS FK*/

/*FK MENU-PLATO*/
ALTER TABLE MENU_PLATOS ADD CONSTRAINT FK_MENU_PLATO_MENU FOREIGN KEY(ID_MENU) REFERENCES MENU(ID_MENU);
ALTER TABLE MENU_PLATOS ADD CONSTRAINT FK_MENU_PLATO_PLATO FOREIGN KEY (ID_PLATOS) REFERENCES PLATOS(ID_PLATOS);

/*FK PLATOS*/
ALTER TABLE PLATOS ADD CONSTRAINT FK_PLATOS_INGREDIENTES FOREIGN KEY(ID_INGREDIENTE) REFERENCES INGREDIENTES(ID_INGREDIENTE);

/*FK RESERVAS*/
ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_CLIENTE FOREIGN KEY (ID_CLIENTE)REFERENCES CLIENTES(ID_CLIENTE);

ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_MENU FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU);

